#### 异常基本语法
```cpp
int myDivide(int a , int b)
{
	if ( b == 0)
	{
		//return -1; //C语言处理异常缺陷在于  返回的值 没有统一，返回的值可以是异常的结果，也可以是正确的结果

		//抛出异常
		//throw 1;
		//throw 3.14;
		//throw 'a';
	}

	return a / b;

}
void test01()
{
	int a = 10;
	int b = 0;

	//尝试执行一段 可能会出现异常的代码
	try
	{
		int ret = myDivide(a, b);
		cout << "ret 结果为： " << ret << endl;
	}
	catch (int ) //捕获异常
	{
		cout << "int类型的异常的捕获" << endl;
	}
	catch (double) 
	{
		throw;//捕获到double后 不想处理这个异常，想继续向上抛出这个异常
		cout << "double类型的异常的捕获" << endl;
	}
	catch (...)
	{
		cout << "其他类型异常的捕获" << endl;
	}

}
int main(){

	try
	{
		test01();
	}
	catch (int) //异常必须有人要处理，如果没有任何的处理，程序会自动调用一个terminate函数，让程序中断掉
	{
		cout << "main函数中的 int类型的异常的捕获" << endl;
	}
	catch (...)
	{
		cout << "mian函数中的 其他类型异常的捕获" << endl;
	}

	return 0;
}
```

#### 抛出自定义异常
```cpp
class MyException
{
public:
	void printError()
	{
		cout << "自定义异常类的错误" << endl;
	}
};
int myDivide(int a , int b)
{
	if ( b == 0)
	{
		throw MyException(); //抛出一个 MyException 匿名对象
	}

	return a / b;
}
void test01()
{
	catch (MyException e)
	{
		e.printError();
	}

}
```

#### 栈解旋
异常被抛出后，从进入try块起，到异常被抛掷前，这期间在栈上的构造的所有对象，都会被自动析构。析构的顺序与构造的顺序相反。这一过程称为栈的解旋(unwinding)
```cpp
class Person
{
public:
	Person()
	{
		cout << "Person的构造函数" << endl;
	}

	~Person()
	{
		cout << "Person的析构函数" << endl;
	}

};
int myDivide(int a , int b)
{
	if ( b == 0)
	{
		//栈解旋： 从try代码块开始起，到 throw抛出异常前，所有栈上的对象都被释放掉，
		//	       释放的顺序和构造的顺序是相反的，这个过程称为栈解旋
		Person p1;//先析构
		Person p2;
		throw MyException(); //抛出一个 MyException 匿名对象
	}
	return a / b;
}
```

#### 异常接口声明
```cpp
void func()throw(double) //只允许 func中抛出 double类型异常 ,如果throw中写() 代表不允许抛出异常
{
   // throw 1;
}

int main(int argc, char *argv[])
{
	try
    {
        func();
    }
    catch(int)
    {
        cout << "int类型异常捕获" << endl;
    }
    catch(double)
    {
        cout << "double类型异常捕获" << endl;
    }

    return 0;
}
```

#### 异常变量的生命周期
```cpp
class MyException
{
public:
	MyException()
	{
		cout << "MyException构造函数调用" << endl;
	}

	MyException(const MyException & e)
	{
		cout << "MyException拷贝构造函数调用" << endl;
	}

	~MyException()
	{
		cout << "MyException的析构函数调用" << endl;
	}
};

void doWork()
{
	throw MyException();
}
void test01()
{
	try
	{
		doWork();
	}
	//catch (MyException e)  会调用拷贝构造
	//catch (MyException &e) 引用方式 接收  建议用这种方式  节省开销
	//catch (MyException *e) 指针方式 接收  抛出 throw &MyException();匿名对象，对象被释放掉，不可以再操作e了
	//catch (MyException *e) 指针方式 接收  抛出 throw new MyException(); 堆区创建的对象  记得手动释放 delete e;
	catch (MyException &e)//建议用这种方式  节省开销
	{
		cout << "MyException的异常捕获" << endl;

	}
}
```

#### 异常的多态
```cpp
//异常 基类
class BaseException
{
public:
	virtual void printError() = 0;
};

//空指针 异常 
class NULLPointException :public BaseException
{
public:
	virtual void printError()
	{
		cout << "空指针异常" << endl;
	}
};

//越界异常
class OutOfRangeException :public BaseException
{
public:
	virtual void printError()
	{
		cout << "越界异常" << endl;
	}
};

void doWork()
{
	//throw NULLPointException();
	throw OutOfRangeException();
}

void test01()
{
	try
	{
		doWork();
	}
	catch (BaseException & e)
	{
		e.printError();
	}
}
```

#### 系统标准异常类
```cpp
#include <stdexcept> //系统标准异常头文件
class Person
{
public:

	Person(int age)
	{
		if (age < 0 || age > 150)
		{
			//年龄越界异常抛出
			//throw out_of_range("年龄必须在 0 到 150之间！");
			throw length_error("年龄必须在 0 到 150之间！");
		}
		this->m_Age = age;
	}
	int m_Age;
};

void test01()
{
	try
	{
		Person p1(151);
	}
	catch (exception & e)
	{
		//所有的异常类都有一个what()方法，返回const char* 类型（C风格字符串）的值，描述异常信息
		cout << e.what() << endl;
	}

}
```
#### 编写自定义异常类(继承 exception)
```cpp
//自己的异常类
class myOutOfRange :public exception
{
public:
	myOutOfRange(char * errorInfo)
	{
		//将char * 转为 string
		this->m_ErrorInfo = string(errorInfo);
	}

	myOutOfRange(string errorInfo)
	{
		this->m_ErrorInfo = errorInfo;
	}

	virtual  ~myOutOfRange()
	{
	}

	const char *  what() const
	{
		//string 转为 const char *
		//.c_str();
		return this->m_ErrorInfo.c_str();
	}

	//保存住 用户传入的异常信息的 字符串
	string m_ErrorInfo;

};

class Person
{
public:

	Person(int age)
	{
		if (age < 0 || age > 150)
		{
			//年龄越界异常抛出
			throw myOutOfRange(  "我的异常类 ---- 年龄必须在 0 到 150 之间");
		}
		this->m_Age = age;
	}

	int m_Age;
};

void test01()
{
	try
	{
		Person p1(1111);
	}
	catch (exception & e)
	{
		cout << e.what() << endl;
	}
}
```